server:  port: 8080  ssl:   key-store: F:/ssl/keystore.p12   key-store-password: azerty   keyStoreType: PKCS12   keyAlias: tomcat
spring:
  
        
  #main:
    #lazy-initialization : true
  datasource:
        url: jdbc:postgresql://localhost:5432/itcompanion
        username: postgres
        password: Herinihaja96
        platform: postgres
        
  jpa:
        database: POSTGRESQL
        show-sql: true
        generate-ddl : true
        hibernate:
            ddl-auto: update
        properties:
                  hibernate:
                            jdbc:
                                  lob: 
                                      non_contextual_creation : true
  security:
    oauth2:
      client:
        registration:         
          facebook:
            client-id: 335487237644838
            client-secret: 2e8abbadf81fbd8f038a96a798647a34
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: public_profile, email
        provider:
          facebook:           
            authorization-uri:  https://www.facebook.com/dialog/oauth
            token-uri: https://graph.facebook.com/v3.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    #myandroidapp://oauth2/redirect
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - itcompanion://oauth2      
       
         
